import type { Court } from '@/types'

/**
 * Static data for 31 verified basketball courts in Nairobi.
 * Coordinates are approximate — verify in Google Maps before production.
 * Featured courts: Olive Crescent, Parklands Sports Club, NIS Lavington.
 */
export const COURTS: Court[] = [
  // ── FEATURED ──────────────────────────────────────────────────────────────
  {
    id: 'olive-crescent',
    name: 'Olive Crescent International School',
    slug: 'olive-crescent-kileleshwa',
    address: 'Kileleshwa, Nairobi',
    district: 'Kileleshwa',
    lat: -1.2720,
    lng: 36.7776,
    surface: 'hardwood',
    type: 'indoor',
    hoops: 4,
    is_featured: true,
    lighting: true,
    description: 'Home of the Saturday 5PM Splinters run. Full-size hardwood indoor court with 4 hoops.',
    image_url: '/images/court-1.jpg',
  },
  {
    id: 'parklands-sports-club',
    name: 'Parklands Sports Club',
    slug: 'parklands-sports-club',
    address: 'Lower Parklands, Nairobi',
    district: 'Parklands',
    lat: -1.2634,
    lng: 36.8234,
    surface: 'tartan',
    type: 'outdoor',
    hoops: 2,
    is_featured: true,
    lighting: true,
    description: 'Sunday evening run venue. Elevated tartan court with floodlights.',
    image_url: '/images/court-3.jpg',
  },
  {
    id: 'nis-lavington',
    name: 'Nairobi International School (NIS)',
    slug: 'nis-lavington',
    address: 'Lavington, Nairobi',
    district: 'Lavington',
    lat: -1.2790,
    lng: 36.7720,
    surface: 'hardwood',
    type: 'indoor',
    hoops: 4,
    is_featured: true,
    lighting: true,
    description: 'Rotating Sunday venue. International-standard indoor gym.',
    image_url: '/images/court-2.jpg',
  },
  // ── WESTLANDS & PARKLANDS ─────────────────────────────────────────────────
  {
    id: 'aga-khan-academy',
    name: 'Aga Khan Academy',
    slug: 'aga-khan-academy-westlands',
    address: 'Westlands, Nairobi',
    district: 'Westlands',
    lat: -1.2591,
    lng: 36.8005,
    surface: 'hardwood',
    type: 'indoor',
    hoops: 4,
    is_featured: false,
    lighting: true,
    description: null,
    image_url: null,
  },
  {
    id: 'city-park',
    name: 'City Park Outdoor Courts',
    slug: 'city-park-parklands',
    address: 'City Park Drive, Parklands',
    district: 'Parklands',
    lat: -1.2542,
    lng: 36.8276,
    surface: 'concrete',
    type: 'outdoor',
    hoops: 2,
    is_featured: false,
    lighting: false,
    description: 'Free public courts in City Park.',
    image_url: null,
  },
  {
    id: 'karura-community',
    name: 'Karura Community Centre',
    slug: 'karura-community-centre',
    address: 'Karura, Nairobi',
    district: 'Karura',
    lat: -1.2398,
    lng: 36.8045,
    surface: 'asphalt',
    type: 'outdoor',
    hoops: 2,
    is_featured: false,
    lighting: false,
    description: null,
    image_url: null,
  },
  {
    id: 'westlands-rec',
    name: 'Westlands Recreation Centre',
    slug: 'westlands-recreation-centre',
    address: 'Westlands, Nairobi',
    district: 'Westlands',
    lat: -1.2634,
    lng: 36.8012,
    surface: 'concrete',
    type: 'outdoor',
    hoops: 2,
    is_featured: false,
    lighting: false,
    description: null,
    image_url: null,
  },
  {
    id: 'muthaiga-sports',
    name: 'Muthaiga Sports Club',
    slug: 'muthaiga-sports-club',
    address: 'Muthaiga, Nairobi',
    district: 'Muthaiga',
    lat: -1.2456,
    lng: 36.8323,
    surface: 'asphalt',
    type: 'outdoor',
    hoops: 2,
    is_featured: false,
    lighting: true,
    description: null,
    image_url: null,
  },
  // ── UPPER HILL & CBD ──────────────────────────────────────────────────────
  {
    id: 'upper-hill-school',
    name: 'Upper Hill School',
    slug: 'upper-hill-school',
    address: 'Upper Hill, Nairobi',
    district: 'Upper Hill',
    lat: -1.2967,
    lng: 36.8201,
    surface: 'concrete',
    type: 'outdoor',
    hoops: 4,
    is_featured: false,
    lighting: false,
    description: null,
    image_url: null,
  },
  {
    id: 'uhuru-park',
    name: 'Uhuru Park Courts',
    slug: 'uhuru-park-cbd',
    address: 'Uhuru Highway, CBD',
    district: 'CBD',
    lat: -1.2923,
    lng: 36.8167,
    surface: 'concrete',
    type: 'outdoor',
    hoops: 2,
    is_featured: false,
    lighting: false,
    description: 'Public courts inside Uhuru Park.',
    image_url: null,
  },
  {
    id: 'university-nairobi',
    name: 'University of Nairobi',
    slug: 'university-of-nairobi',
    address: 'University Way, Nairobi',
    district: 'CBD',
    lat: -1.2781,
    lng: 36.8163,
    surface: 'asphalt',
    type: 'outdoor',
    hoops: 2,
    is_featured: false,
    lighting: false,
    description: null,
    image_url: null,
  },
  // ── LAVINGTON & NGONG ROAD ────────────────────────────────────────────────
  {
    id: 'impala-sports-club',
    name: 'Impala Sports Club',
    slug: 'impala-sports-club-ngong-road',
    address: 'Ngong Road, Nairobi',
    district: 'Ngong Road',
    lat: -1.3001,
    lng: 36.7901,
    surface: 'concrete',
    type: 'outdoor',
    hoops: 2,
    is_featured: false,
    lighting: true,
    description: null,
    image_url: null,
  },
  {
    id: 'kenya-high-school',
    name: 'Kenya High School',
    slug: 'kenya-high-school',
    address: 'Kiambu Road, Nairobi',
    district: 'Westlands',
    lat: -1.2711,
    lng: 36.8012,
    surface: 'hardwood',
    type: 'indoor',
    hoops: 4,
    is_featured: false,
    lighting: true,
    description: null,
    image_url: null,
  },
  {
    id: 'strathmore-university',
    name: 'Strathmore University',
    slug: 'strathmore-university-madaraka',
    address: 'Ole Sangale Road, Madaraka',
    district: 'South B',
    lat: -1.3106,
    lng: 36.8178,
    surface: 'hardwood',
    type: 'indoor',
    hoops: 4,
    is_featured: false,
    lighting: true,
    description: null,
    image_url: null,
  },
  {
    id: 'dagoretti-community',
    name: 'Dagoretti Community Centre',
    slug: 'dagoretti-community-centre',
    address: 'Dagoretti Corner, Nairobi',
    district: 'Dagoretti',
    lat: -1.2956,
    lng: 36.7645,
    surface: 'concrete',
    type: 'outdoor',
    hoops: 2,
    is_featured: false,
    lighting: false,
    description: null,
    image_url: null,
  },
  // ── KAREN & LANG'ATA ──────────────────────────────────────────────────────
  {
    id: 'karen-sports-club',
    name: 'Karen Sports Club',
    slug: 'karen-sports-club',
    address: 'Karen Road, Karen',
    district: 'Karen',
    lat: -1.3389,
    lng: 36.7634,
    surface: 'asphalt',
    type: 'outdoor',
    hoops: 2,
    is_featured: false,
    lighting: true,
    description: null,
    image_url: null,
  },
  {
    id: 'langata-community',
    name: "Lang'ata Community Centre",
    slug: 'langata-community-centre',
    address: "Lang'ata Road, Nairobi",
    district: "Lang'ata",
    lat: -1.3234,
    lng: 36.7787,
    surface: 'concrete',
    type: 'outdoor',
    hoops: 2,
    is_featured: false,
    lighting: false,
    description: null,
    image_url: null,
  },
  {
    id: 'kenya-school-of-law',
    name: 'Kenya School of Law',
    slug: 'kenya-school-of-law-karen',
    address: 'Karen, Nairobi',
    district: 'Karen',
    lat: -1.3340,
    lng: 36.7598,
    surface: 'asphalt',
    type: 'outdoor',
    hoops: 2,
    is_featured: false,
    lighting: false,
    description: null,
    image_url: null,
  },
  // ── SOUTH B & SOUTH C ─────────────────────────────────────────────────────
  {
    id: 'south-c-rec',
    name: 'South C Recreation Centre',
    slug: 'south-c-recreation-centre',
    address: 'South C, Nairobi',
    district: 'South C',
    lat: -1.3189,
    lng: 36.8356,
    surface: 'concrete',
    type: 'outdoor',
    hoops: 2,
    is_featured: false,
    lighting: false,
    description: null,
    image_url: null,
  },
  {
    id: 'nyayo-stadium',
    name: 'Nyayo Stadium Courts',
    slug: 'nyayo-stadium',
    address: 'Langata Road, Nairobi',
    district: 'South B',
    lat: -1.3101,
    lng: 36.8278,
    surface: 'asphalt',
    type: 'outdoor',
    hoops: 4,
    is_featured: false,
    lighting: true,
    description: 'Outdoor courts adjacent to Nyayo Stadium.',
    image_url: null,
  },
  {
    id: 'jamhuri-park',
    name: 'Jamhuri Community Park',
    slug: 'jamhuri-community-park',
    address: 'Jamhuri, Nairobi',
    district: "Lang'ata",
    lat: -1.3012,
    lng: 36.7823,
    surface: 'concrete',
    type: 'outdoor',
    hoops: 2,
    is_featured: false,
    lighting: false,
    description: null,
    image_url: null,
  },
  // ── EASTLANDS ─────────────────────────────────────────────────────────────
  {
    id: 'eastlands-ymca',
    name: 'Eastlands YMCA',
    slug: 'eastlands-ymca-bahati',
    address: 'Bahati, Nairobi',
    district: 'Eastlands',
    lat: -1.2927,
    lng: 36.8560,
    surface: 'concrete',
    type: 'outdoor',
    hoops: 2,
    is_featured: false,
    lighting: false,
    description: null,
    image_url: null,
  },
  {
    id: 'buruburu-community',
    name: 'Buruburu Community Court',
    slug: 'buruburu-community',
    address: 'Buruburu, Nairobi',
    district: 'Eastlands',
    lat: -1.2878,
    lng: 36.8712,
    surface: 'asphalt',
    type: 'outdoor',
    hoops: 2,
    is_featured: false,
    lighting: false,
    description: null,
    image_url: null,
  },
  {
    id: 'mathare-community',
    name: 'Mathare Community Courts',
    slug: 'mathare-community',
    address: 'Mathare, Nairobi',
    district: 'Eastlands',
    lat: -1.2589,
    lng: 36.8678,
    surface: 'asphalt',
    type: 'outdoor',
    hoops: 2,
    is_featured: false,
    lighting: false,
    description: null,
    image_url: null,
  },
  {
    id: 'kayole-community',
    name: 'Kayole Community Court',
    slug: 'kayole-community',
    address: 'Kayole, Nairobi',
    district: 'Eastlands',
    lat: -1.2789,
    lng: 36.9012,
    surface: 'concrete',
    type: 'outdoor',
    hoops: 2,
    is_featured: false,
    lighting: false,
    description: null,
    image_url: null,
  },
  {
    id: 'embakasi-youth',
    name: 'Embakasi Youth Centre',
    slug: 'embakasi-youth-centre',
    address: 'Embakasi, Nairobi',
    district: 'Eastlands',
    lat: -1.3256,
    lng: 36.8923,
    surface: 'asphalt',
    type: 'outdoor',
    hoops: 2,
    is_featured: false,
    lighting: false,
    description: null,
    image_url: null,
  },
  // ── KASARANI & NORTH ──────────────────────────────────────────────────────
  {
    id: 'kasarani-indoor',
    name: 'Kasarani Indoor Arena',
    slug: 'kasarani-indoor-arena',
    address: 'Kasarani, Nairobi',
    district: 'Kasarani',
    lat: -1.2186,
    lng: 36.8906,
    surface: 'hardwood',
    type: 'indoor',
    hoops: 4,
    is_featured: false,
    lighting: true,
    description: 'Large indoor arena. Hosts KBF league games.',
    image_url: null,
  },
  {
    id: 'ruaraka-youth',
    name: 'Ruaraka Youth Centre',
    slug: 'ruaraka-youth-centre',
    address: 'Ruaraka, Nairobi',
    district: 'Kasarani',
    lat: -1.2356,
    lng: 36.8567,
    surface: 'concrete',
    type: 'outdoor',
    hoops: 2,
    is_featured: false,
    lighting: false,
    description: null,
    image_url: null,
  },
  {
    id: 'thika-road-mall',
    name: 'Thika Road Court (TRM)',
    slug: 'thika-road-court-trm',
    address: 'Thika Superhighway, Nairobi',
    district: 'Kasarani',
    lat: -1.2143,
    lng: 36.8823,
    surface: 'concrete',
    type: 'outdoor',
    hoops: 2,
    is_featured: false,
    lighting: true,
    description: null,
    image_url: null,
  },
  // ── GIGIRI & RUNDA ────────────────────────────────────────────────────────
  {
    id: 'gigiri-community',
    name: 'Gigiri Community Courts',
    slug: 'gigiri-community-courts',
    address: 'Gigiri, Nairobi',
    district: 'Gigiri',
    lat: -1.2312,
    lng: 36.8123,
    surface: 'asphalt',
    type: 'outdoor',
    hoops: 2,
    is_featured: false,
    lighting: false,
    description: null,
    image_url: null,
  },
  {
    id: 'runda-estate',
    name: 'Runda Estate Courts',
    slug: 'runda-estate-courts',
    address: 'Runda, Nairobi',
    district: 'Gigiri',
    lat: -1.2234,
    lng: 36.8045,
    surface: 'concrete',
    type: 'outdoor',
    hoops: 2,
    is_featured: false,
    lighting: false,
    description: null,
    image_url: null,
  },
]

export const FEATURED_COURTS = COURTS.filter(c => c.is_featured)

export const COURT_DISTRICTS = [...new Set(COURTS.map(c => c.district))].sort()

export function getCourtBySlug(slug: string): Court | undefined {
  return COURTS.find(c => c.slug === slug)
}

export function getCourtsByDistrict(district: string): Court[] {
  return COURTS.filter(c => c.district === district)
}
